# Site settings
title: Yann Dubois
header-img: img/home-bg.jpg
email: yanndubois96@gmail.com
description: "Yann Dubois' blog, with focus on machine learning (Yet another ;D)"
baseurl: ""
url: "https://yanndubs.github.io/"
twitter_username: yanndubs
github_username:  YannDubs
linkedin_username:  duboisyann
email_username:  yanndubois96@gmail.com
# facebook_username: 

# Disqus:
disqus: https-yanndubs-github-io
# Google Analytics
google_tracking_id: UA-108456313-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
